server:
  port: 19094

spring:
  application:
    name: order-service

  config:
    import:
      - optional:file:.env[.properties]
      - classpath:properties/datasource.yml
      - classpath:properties/jpa.yml
      - classpath:properties/eureka-client.yml
      - classpath:properties/actuator.yml