server:
  port: 19094

spring:
  application:
    name: order-service

  config:
    import:
      - optional:file:.env[.properties]
      - classpath:properties/jpa.yml
      - classpath:properties/datasource.yml
      - classpath:properties/eureka-client.yml

logging:
  level:
    # 클라이언트 패키지 로깅
    com.sparta.limited.auction_service.Auction_product.infrastructure.client: DEBUG
    # Feign 전체 로깅
    org.springframework.cloud.openfeign: DEBUG
    # Feign 요청/응답 로깅
    feign: DEBUG
    # 추가적으로 유용할 수 있는 로깅
    org.springframework.web: DEBUG